### ISSUE TITLE
Sample App not working

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/CompuMaster.CenterDevice.IO#1]
## ToDos

- [ ] implementation for authentification missing
- [ ] working sample code implementation missing
- [ ] working sample code to be documented in README file
